api_projects:
    type: rest
    resource: "@ManagementBundle/Controller/ProjectController.php"
    name_prefix:   api_project_
    prefix:    project

api_stories:
    type: annotation
    resource: "@ManagementBundle/Controller/StoryController.php"
    name_prefix:   api_story_
api_stories:
    type: annotation
    resource: "@ManagementBundle/Controller/SprintController.php"
    name_prefix:   api_sprint_
#    prefix:    story

