security:

    role_hierarchy:
        #Herencia de roles

        #ROLES DEL ÁREA DE GESTIÓN
        ROLE_USER:   ROLE_USER
        ##ADMINISTRADOR ACCESO
        ROLE_SUPER_ADMIN:    [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
         fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: redirect_to_path
            logout:
                path:   /logout
                target: /login
                # the authenticated session will be unavailable afterwards
                invalidate_session: true

            anonymous:    true

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #El orden implica precedencia
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }



