<?php

namespace ManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessProcessesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessProcessesRepository extends EntityRepository
{
}
