<?php

namespace ManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MeetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetRepository extends EntityRepository
{
}
