<?php

namespace ManagementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpendEffortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpendEffortRepository extends EntityRepository
{
}
